### ISSUE TITLE
data

### ISSUE THREAD

**Issue by luoluoluoyl** [ndionysus/twitter-cyberthreat-detection#2]
Dear author, I am very interested in your research. Could you please share your original tweet data for my reference? If possible, my email is 780126606@qq.com

**Comment by ndionysus** [comment]
Hello @luoluoluoyl , thank you for your interest!
Apologies, I have been busy and couldn't respond to your request sooner, but I would like to point to a new version of the repository which has the complete data available instead of just the Twitter ids. 
https://github.com/ndionysus/multitask-cyberthreat-detection

Hopefully soon I will have more time to update the repo above. But in the meantime you can use the data from there.
Let me know if you need anything else from my end!
